name: macOS Build

on:
  push:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: Apple Darwin Build
    strategy:
      fail-fast: false
      matrix:
        # Intel + Apple Silicon
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
      target: ${{ matrix.target }}
